### ISSUE TITLE
FPS drops to 0 fps for a while after closing any menu

### ISSUE THREAD

**Issue by primussejati** [HolographicWings/TOTK-Mods-collection#106]
Following all settings and mods instruction from guide.pdf excep DLDSR  because no DSR factor menu in my 3D settings
My laptop specification is : 
Asus TUF Gaming FA506IC
GPU : Nvidia Geforce RTX 3050 4gb
CPU : AMD Ryzen 7 4800H
RAM : 16 Gb DDR4 3200
Using ssd
Yuzu EA 3647 (I always automatically update my emu)
Game ver 1.1.2

I already tried using controller mod but the problem still exist.

**Comment by primussejati** [comment]
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/75939710/2326c2a9-5c16-4a37-828b-d4d41afb5e27)
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/75939710/2f8768f2-80e1-434a-9b6d-6b6e7c0ab5e1)
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/75939710/a55c83a3-f309-4eb5-8593-ec60283a36b2)

**Comment by JunieXD** [comment]
Me too

**Comment by SpockBauru** [comment]
Try to set your ASTC recompression according to the written guide: 
https://github.com/HolographicWings/TOTK-Mods-collection/blob/main/SETUP.md

Also notebook hardware are usually a way weaker than their Desktop counterparts, try lowering some settings like use 30fps Static instead of 60 and Resolution 1x instead of 2

**Comment by SpockBauru** [comment]
Laptop hardware are usually a way weaker than their desktop counterparts. Try lowering some settings like:
Use the mod 30fps Static instead of 60
Use Resolution 1x instead of 2
Use ASTC Recompression BC1 (last resource)

Also remove your "Cache Storage" and "Pipeline Caches" (right click in the game -> remove)

If doesn't help, I have absolutely no idea...
