### ISSUE TITLE
Crash when using 1080p Mod and Shadows 1024x Mod together

### ISSUE THREAD

**Issue by rarikuma** [HolographicWings/TOTK-Mods-collection#107]
When running 1080p Mod and Shadows 1024x Mod on Yuzu, crash occurs when trying to run Ascend while running Recall on Eldin Canyon Depth.

We have confirmed that the crash occurs only with the above Mod combination.
It does not crash with 1080p Mod alone or Shadows 1024x Mod alone.
The crash does not occur when the 1008p Mod and Shadows 1024x Mod are used together.

https://github.com/HolographicWings/TOTK-Mods-collection/assets/135856005/2b02a3a6-f0aa-449b-91ee-4391c43a7459

![0100f2c0115b6000_2023-06-08_01-19-00-214](https://github.com/HolographicWings/TOTK-Mods-collection/assets/135856005/7c2e8189-65ad-488b-95da-42ee7802b8cb)

![20230608012746](https://github.com/HolographicWings/TOTK-Mods-collection/assets/135856005/a3ec2558-4f75-40df-8cb4-2754b46a2450)

Yuzu EA3645
Zelda ToTK Ver. 1.1.2
TOTK-Mods-collection v1.9.2.3

CPU: 12th Gen Intel(R) Core(TM) i7-12700K 3.60 GHz
GPU/Driver: NVIDIA Geforce RTX 4090/Game Ready Driver 532.03
RAM: 32.0 GB
OS: Windows 11 Enterprise 22H2 22621.1702

### Log File
[yuzu_log.zip](https://github.com/HolographicWings/TOTK-Mods-collection/files/11685908/yuzu_log.zip)

**Comment by HolographicWings** [comment]
You have alot of HW.Memory <Error> core\memory.cpp:operator ():655: Unmapped Read64 @ 0x0000000000000008 errors
I can advice you to backup your shader cache and try to reset it, otherwise i don't know what happening

**Comment by rarikuma** [comment]
After resetting the shader cache, the crash no longer occurs when using 1080p Mod and Shadows 1024x Mod together.
Thanks.

**Comment by rarikuma** [comment]
I reset the shader cache and tried again with 1080p Mod and Shadows 1024x Mod together and got the same crash.

### Log File
[yuzu_log.zip](https://github.com/HolographicWings/TOTK-Mods-collection/files/11704211/yuzu_log.zip)

**Comment by hoverbike1** [comment]
I've been testing this for a few days now.
3645, 1.1.2 and 1.1.1
It seems the issue persists across versions.
So I decided to try my lazy packs - since I don't have that issue normally.
Something, which I haven't been able to figure out, since all of my theories were unsuccesful in causing the issue in the lazy packs - no amount of reordering the loading of patches did anything to recreate the issue.
So while I can't tell you what the actual issue is, the best I can do, is to offer a solution.

You can downgrade to patch 1.1.1 with no issues, as I have done in testing - shaders are compatible between 1.1.0-1.1.2 - just not the base game version.

Use my lazy packs. For you, i'd suggest the 60 FPS 1080P versions, with UI Mod Compatibility if you use UI Mods such as the Playstation UI Mod like I do.

This is what my modlist looks like, its just the lazy pack with a bunch of cheats.
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/57139770/70b345b7-5630-4bfa-9b6b-1531c453de0e)
Try out the lazy pack, see if it solves your issue as well.

**Comment by SpockBauru** [comment]
WE FOUND IT!!! 
Hoverbike and I discovered that if you use the Disable Targeting DOF when using 1080p and shadows 1024x the game don't freezes. So the solution for now is to always use Disable Targeting DOF when using Resolution 1080p and shadows 1024x
:D
