### ISSUE TITLE
Low res prerendered cutscenes?

### ISSUE THREAD

**Issue by GuyGieri** [HolographicWings/TOTK-Mods-collection#144]
Hey,

The lazy mod patch creator worked great. Im playing at 4k 60fps on a 3070ti and everythings going well. The only thing is that during what I assume is a pre-rendered cutscene where zelda/link interact with the main villain during the opening, is it is 1080p and looks pretty terrible. Is there a way to fix this or just a result of the cutscene blown up on a much larger screen than intended?

**Comment by SpockBauru** [comment]
The only way would be to update the video files themselves. Unfortunately nobody did this mod yet.

**Comment by hoverbike1** [comment]
if you go to the /event/movie/ directory, you'll find all the cutscenes in totk.
they're all vp9 webm files.
using this tool: https://github.com/AaronFeng753/Waifu2x-Extension-GUI
you could try upscaling them to 4K and see if you like the result.

**Comment by GuyGieri** [comment]
Hey man, I downloaded but couldnt find that directory. Do you mind being more specific of where to find it? I checked my appdata-roaming-yuzu as well as nsp locations but no luck.

**Comment by hoverbike1** [comment]
C:\Users\<Your Username>\AppData\Roaming\yuzu\dump\0100F2C0115B6000\romfs\Event\Movie
If you find that the "dump" directory does not exist for you, or the game ID "0100F2C0115B6000" (TOTK) folder does not exist, it is because you need to open yuzu, right click TOTK, and select "Dump RomFS -> Dump RomFS"
You want to create a full dump, if prompted, and not a skeleton.
This will produce the files that you are looking for.

**Comment by GuyGieri** [comment]
Got it, the files are currently dumping and then I will upscale them. Is there any additional steps after this? Undumping or something like that

**Comment by hoverbike1** [comment]
well, some things to keep in mind: dont interpolate the framerate to 60, unless you want to go through the bother of editing event files for audio, since audio is scripted to play at a certain frame of the videos they're attached to. you might be able to scrounge something from pixelkiri's original post about 60 fps interpolated cutscenes.

once youve generated the files, and youre happy with them, you'll need to construct a "romfs" mod.
you do this by creating a folder labeled with your desired mod name
in this folder, you'll want to create a "romfs" folder, and inside this romfs folder, construct an exact copy of where the files are stored in the dump of the game.
e.g., for the "Dm_BC_0012_PreRender" file, which is the first cutscene you see in the game, the folder structure should look as such:
"C:/Users/<Your Username>/AppData/Roaming/yuzu/load/0100F2C0115B6000/<Your mod name>/romfs/Event/Movie/Dm_BC_0012_PreRender.webm"

**Comment by GuyGieri** [comment]
Hey man, thanks for the guidance. I tried upscaling but it was taking forever. Turned on hardware acceleration and all that but still nothing, I have a 3070ti and 5800x3d so I was a bit surprised but whatever. In the end it started working and after an hour gave an estimate of 20 hours to compete so I think Im going to just deal with the 1080p, but thanks for the help regardless.

**Comment by hoverbike1** [comment]
Yeah, thats sort of unavoidable.
The program literally splits the video file frame by frame, and then uses the waifu2x upscaling method. Assume upscaling 1 frame takes 2 minutes. This is a pretty reasonable estimate.
That means that to upscale 1 second of 30 fps footage... takes an hour.
1 second of 30 frames, x 2 minutes = 60 minutes.
Now just multiply that by the amount of seconds of footage you need to upscale.

When I did it myself, it wasn't even that part that put me off. The worst part is that after having rendered it, I would spot slight issues, correct them, and now guess what...
I gotta upscale the entire thing again now. Hah.
You definitely need patience for this stuff, but its the method that should yield the most desirable result.
