### ISSUE TITLE
Misinformation about resolution scale

### ISSUE THREAD

**Issue by WilliamTael** [HolographicWings/TOTK-Mods-collection#145]
Info on the guide: "Resolution: 1x. Don't change this, mods do a better job at scaling resolution." 
Even when I'm using the mod "DynamicFPS - v1.5.5 - 2560x1440 resolution" the 1x scale will not render at 1440p, it will visibly stay at vanilla res.

**Comment by SpockBauru** [comment]
This is likely caused by wrong configuration, because it really renders at the desired resolution. Did you remembered to enable Configure-> System-> "Unsafe extended memory layout (8GB DRAM)"? (new yuzu is called Mamory Layout -> 8GB)
![ToTK_4k_Resolution](https://github.com/HolographicWings/TOTK-Mods-collection/assets/67930504/5b3faff3-cfb5-440c-a2d6-6a97e1484d4b)

**Comment by WilliamTael** [comment]
Yes. I did just that.

Em ter., 25 de jul. de 2023 22:24, SpockBauru ***@***.***>
escreveu:

**Comment by hoverbike1** [comment]
Try using the lazy pack generator.

**Comment by hoverbike1** [comment]
could also be a bad dump.
if you're using the fatgirl base game dump, go ahead and throw it in the garbage bin, where it belongs.
that crap is so broken i don't know where to start.
