### ISSUE TITLE
No links to original mods

### ISSUE THREAD

**Issue by UdonOli** [HolographicWings/TOTK-Mods-collection#3]
There should be links to the original authors of each mod.

**Comment by Foul-Tarnished** [comment]
yes.
cringe thief.

**Comment by HolographicWings** [comment]
> There should be links to the original authors of each mod.

I'm agreed, but sadly the source of most of them are a real mystery
We don't made mods, we only gather them in same place and keep them updated

**Comment by HolographicWings** [comment]
> yes. cringe thief.

Try to don't insult people thanks you, ask to every people randomly sending mods on the yuzu discord and reddit to send source then, we are unfortunately not diviners
I'll try to investigate on source of them to place URL and owner names but i think the owner themselves will have to come here to ask for credits

**Comment by Julienraptor01** [comment]
OK this is acknoledge very easily by me who made the initial groups, i took from every patch that existed and many were just zip files on discord, the thing is many people shared things and it's nearly untracable so yeah there are some things which i could find the potential authors but not much
I personally only created the 540p docked and that's all
I also converted the amiibo cheat code to an exefs mod, but it's unsure about that, i did it at like 3am, i was tired and my Brian wasn't able to memorize anymore 

I think the best way to resolve this problem is to do global credits aka :
Thanks to all modders on GBATemp, Yuzu, Ryujinx and private discords for making theses mods

**Comment by Mega-Ryan** [comment]
I'll provide what I know about the sources of these mods. Hope it helps a little.
20/30/60 FPS mod is from somerandompeople on gbatemp.net https://gbatemp.net/download/loz-tears-of-the-kingdom-20fps-30fps-60fps-patch.37996/
dynamic fps mod is from ChucksFeedAndSeed from Reddit https://www.reddit.com/user/ChucksFeedAndSeed/
cutscene fix mod is from theboy181 (not very sure)

**Comment by HolographicWings** [comment]
ChucksFeedAndSeed, patchanon and somerandompeople works together, i credited them together on the README

**Comment by ExistsOnline** [comment]
Linking to original creators when necessary is good but I just wanted to say I really appreciate this collecting of them since some are hard to find. Good job!

**Comment by Dark-talon** [comment]
We've linked as many as we can, but we will not be linking to places associated with piracy ever.
