### ISSUE TITLE
Add 60fps black screen fix mod

### ISSUE THREAD

**Issue by iAbadia** [HolographicWings/TOTK-Mods-collection#4]
Reddit used posted it overnight: https://www.reddit.com/r/NewYuzuPiracy/comments/13hq70a/60_fps_mod_black_screen_fix_not_thoroughly_tested/

**Comment by HolographicWings** [comment]
Hello, sadly i can't add it, this mod share an edited file from the game RomFS, it's illegal sorry.

**Comment by Julienraptor01** [comment]
The dynamic 60fps mod should be added (the black screen fix)
But the Cutscene fix maybe isn't legal and we don't want to get in trouble so it won't be linked for sure

**Comment by hoverbike1** [comment]
I need to be able to view the contents of these files in order to see if they contain any code left over from the files they were ripped from.

If any code still remains, it is code copyrighted by Nintendo, and we *cannot under any circumstance* distribute such.

![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/57139770/02882dff-766d-469a-ab90-6e1cdfda6502)

On the left, middle file, is the same file present in a fresh romFS dump. 5988 KB.
On the right, is the same file, present in the 60fpsblackscreen patch. 6070 KB.
Now, admittedly, i'm no coding expert, but, even from this, I can go out on a limb and say, he probably added about 100 KB of his own code to that file - and everything else is Nintendos. 

And sharing it would be very illegal.

**Comment by Julienraptor01** [comment]
> I need to be able to view the contents of these files in order to see if they contain any code left over from the files they were ripped from.
> 
> If any code still remains, it is code copyrighted by Nintendo, and we *cannot under any circumstance* distribute such.
> 
> ![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/57139770/02882dff-766d-469a-ab90-6e1cdfda6502)
> 
> On the left, middle file, is the same file present in a fresh romFS dump. 5988 KB.
> On the right, is the same file, present in the 60fpsblackscreen patch. 6070 KB.
> Now, admittedly, i'm no coding expert, but, even from this, I can go out on a limb and say, he probably added about 100 KB of his own code to that file - and everything else is Nintendos. 
> 
> And sharing it would be very illegal.

Could you go on gamebanana, check for BotW switch mods and see how many are Romfs mods ? (spoiler alert, a lot since it isn't illegal) (if it was illegal gamebanana would probably have some problem rn) 
And if i understand correctly RomFS contain data to make the game work not code, code is the ExeFS part
Checking filesize is also a bad idea because Nintendo uses compression, if the dev replaced the entire of the file with custom data, the filesize could be the same, bigger or smaller depending of tte data

**Comment by Julienraptor01** [comment]
This issue will be closed anyway, a [new ExeFS patch](https://cdn.discordapp.com/attachments/495758692495523854/1107914108789075998/Cutscene-Fix.rar) by theboy181 is out

**Comment by iAbadia** [comment]
Thanks for the attention, I agree with @hoverbike1 's concerns. Closing.

**Comment by HolographicWings** [comment]
Sorry to remove, theses topics are not supposed to be here
