### ISSUE TITLE
Can you add in the README a list of recommended configurations ?

### ISSUE THREAD

**Issue by AgentPotatoDev** [HolographicWings/TOTK-Mods-collection#42]
When trying to add mods together the game crashed, and I want it to work for my little bro, please add a list of recommended mods.

**Comment by HolographicWings** [comment]
Hello, what mods did you used ?

Here my advices : 
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/19623115/7e342b1f-3788-41e6-a92b-94776c189b1e)

**Comment by AgentPotatoDev** [comment]
I will try this, thanks. I used this:
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/65216658/28cc3318-5098-403f-8ff9-3a6ec93caa93)
Thanks!

**Comment by HolographicWings** [comment]
Don't use the fsr sharpening remover alone

**Comment by AgentPotatoDev** [comment]
thank you bro 👍

**Comment by baconsplit** [comment]
Hey, I want to add to this thread because I am getting lost with the amount of mods right now.
I want a visually stable and pleasing experience, but with performance in focus.
Could I just get a quick opinion on my selection of mods for this cause? Also, since FXAA usually makes games look more blurry and worse, and yuzu uses SMAA, I disabled it with the v2 Mod in the collection. Is that the correct one?
Lasty, what is about the change to use DXGI Swapchain in the Nvidia Settings for Vulkan? Does this improve any performance or is it just some weird fix people use(d)?
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/63647668/085134d9-7703-46c6-b4d3-f46273257d35)

**Comment by HolographicWings** [comment]
Added a recommended configuration in the documentation, i dunno about DXGI Swapchain sorry, i heard that was about HDR but i'm unsure.
