### ISSUE TITLE
The 30fps 1080p lazy patch includes the DOF targeting mod in ver 1.1.1

### ISSUE THREAD

**Issue by UdonOli** [HolographicWings/TOTK-Mods-collection#56]
There are massive differences between the 1.1.0 and 1.1.1 version patches, with entirely different mods between them.
This is not specified and seems like a bug. I have not checked whether this applies across other lazy packs.

**Comment by HolographicWings** [comment]
I'm assigning Hover on that, it's his pack

**Comment by HolographicWings** [comment]
I'm assigning Hover on that, it's his pack
Otherwise you can made a pull request with a fix too

**Comment by hoverbike1** [comment]
The lazy pack patches for 1.1.0 has not changed since the previous distribution.
The new 1.1.1 lazy packs contain different patches, _because not all patches from 1.1.0 are available in 1.1.1 yet, and vice versa._
The DOF removal is present in the 1.1.1 patches because it improves the fidelity of the presented image, by removing a low-res DOF effect.
This patch is not available for 1.1.0, but should this change, then it will be added at a later date.
This is the first complaint of the DOF mod, so I will consider it acceptable, unless a larger amount of users complain of missing, low-quality DOF.
This applies across all other lazy packs.
