### ISSUE TITLE
stolen mod

### ISSUE THREAD

**Issue by Foul-Tarnished** [HolographicWings/TOTK-Mods-collection#82]
Sky Island fix is from TheBoy, not SweetMini.

Only for patreon or whatever, not public..

**Comment by Graadul** [comment]
> Sky Island fix is from TheBoy, not SweetMini.
> 
> Only for patreon or whatever, not public..

So what? We all now should delete that mod couse somebody create paywall and somebody esle drop that mod for free somewhere on internet?

**Comment by InfiniteParallel** [comment]
Further to the argument that Graadul was making, it is also possible for more than one person to come to the same conclusion independently after analyzing code for a particular issues. We have no way of knowing they didn't come up with the same idea without knowing what the other person was working on.

**Comment by Dark-talon** [comment]
Nothing has been "stolen". Credit has been attributed to the person who researched and created code that solves a long reported problem and works on the latest game patches.

**Comment by HolographicWings** [comment]
@Foul-Tarnished Impossible to check if Sweetmini stole the mod of Theboy or not
In fact, the boy v5 mod is anterior to the sweetmini's one, but theboy only support 1.1.0
sweetmini support 1.1.1 and 1.1.2
That look like a portage

In all cases "stole" code is incorrect, the mod is literally 8 bytes, it's an address and a value overwrite
Theres only one way to edit something in the game by the exefs way, that mean if someone make a mod, everyone making the same discovery will by default copy it's work even without knowing it.
Exemple, to disable FXAA, theres only one way, patching the exact address where FXAA is. Two people making the same mod will fataly write the same things.

It's probable they just both found this address and patched it without copying anything, there is no way to prove anything.
Theboy doesn't protect his mods under licence, it's his own choice to take this risk.
I gave him some advices to sign his mods and keep a potential proof that it's his work so that will be his choice to do it or not.

(Hoping my english was not too bad)
