### ISSUE TITLE
Lazy pack for 1.1.2

### ISSUE THREAD

**Issue by crow-rojas** [HolographicWings/TOTK-Mods-collection#99]
Hi, just asking, is there an estimated date for compatibility of the lazy packs with the 1.1.2 version of the game? Thanks!

**Comment by hoverbike1** [comment]
well, the reason lazy patches aren't at the bleeding edge of versions, is because being lazy involves not bothering with updates, as much, at least.
so as for the when, probably when 1.1.3 hits - since then, the patch work on 1.1.2 stops, and we usually have a pretty decent choice of patches by then.
but yeah also maybe laziness
we will see

**Comment by crow-rojas** [comment]
Thank you for your response 🫶🏻
